BaseURL = "https://linz1989.github.io/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "linz blog"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "zhangjialin"

[Params]
  AuthorHomepage = "https://linz1989.github.io/"
  BottomIntroduce = "Introduce1 <br/> Introduce2"
  Description = "linz web blog"
  Subtitle = "生命可以随心所欲，但不能随波逐流"
  Weibo = ""
  WeiboID = ""
  Twitter = ""
  GitHub = "linz1989"
  Facebook = ""
  LinkIn = ""
  Imglogo = "img/header.jpg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  # [Params.DuoShuo]
  #  ShortName = ""

  [Params.Disqus]
    ShortName = "linz1989githubio"

  [Params.GoogleAnalytics]
    ID = ""

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
   [[Menu.Main]]
    Name = "About Me"
    URL = "/about"
    Weight = 1

    [[Menu.Main]]
      Name = "生活&读书"
      URL = "/life"
      Weight = 2

    [[Menu.Main]]
      Name = "编程&工作"
      URL = "/programming"
      Weight = 3

  [[Menu.Main]]
     Name = "首页"
     URL = "/"
     Weight = 4